#define MAX_LIGHTS 20

#define DEPTH_BUFFER_INDEX 0
#define POS_BUFFER_INDEX 1
#define NORMAL_BUFFER_INDEX 2
#define COLOR_BUFFER_INDEX 3

#define G_BUFFER_SIZE 4

#define SSAO_NOISE_DIM 4
#define SSAO_NUM_SAMPLES 32

#define GAMMA 2.2
